version: '3.5'
services:
  #PHP Service
  app_siov1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_siov1
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - efo_networks
  # Nginx Service
  webserver_sio:
    image: nginx:alpine
    container_name: webserver_sio
    restart: unless-stopped
    tty: true
    ports:
      - "8881:8881"
    volumes:
     - ./:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      efo_networks:
        aliases:
          - service_web
    command: [nginx-debug, '-g', 'daemon off;']
  # POSTGRES CONTAINER
#Docker Networks
volumes:
  dbdata:
    driver: local
  pgdata:
    driver: local
networks:
  efo_networks:
    name: efo_networks
    external: true