version: '3.5'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-test
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - efo_networks
  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8008:8008"
      - "443:443"
    volumes:
     - ./:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      efo_networks:
        aliases:
          - service_web
    command: [nginx-debug, '-g', 'daemon off;']
  # POSTGRES CONTAINER
  postgres:
    image: postgres:14.6-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ilhamefo
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5430:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - efo_networks
#Docker Networks
volumes:
  dbdata:
    driver: local
  pgdata:
    driver: local
networks:
  efo_networks:
    name: efo_networks
    external: true